/*
 * MIT License
 *
 * Copyright (c) 2026 Mellowhue
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.nanitu.ai;

import net.nanitu.ai.spi.ModelProvider;

/**
 * Represents an AI language model that can generate chat completions.
 *
 * <p>A {@code Model} is the main entry point for interacting with an AI service.
 * It abstracts over different backends — cloud APIs (OpenAI, Anthropic),
 * locally hosted inference servers (Ollama, llama.cpp), or any other
 * compatible provider.
 *
 * <p>Models are obtained through the {@link ModelProvider} service provider
 * interface, which uses {@link java.util.ServiceLoader} for automatic discovery:
 *
 * <pre>{@code
 * // Get the first available model
 * Model model = ModelProvider.get(ModelProvider.class).create();
 *
 * // Simple one-shot completion
 * ChatRequest req = new ChatRequest(List.of(ChatMessage.user("Hello")));
 * ChatResponse res = model.chat(req);
 * System.out.println(res.content());
 * }</pre>
 *
 * <p>For streaming responses, use {@link #chatStream(ChatRequest, StreamHandler)}:
 *
 * <pre>{@code
 * model.chatStream(request, new StreamHandler() {
 *     public void onToken(String token) { System.out.print(token); }
 * });
 * }</pre>
 *
 * <p>For multi-turn conversations, use {@link #createContext()} to obtain a
 * {@link Context} that automatically manages message history:
 *
 * <pre>{@code
 * Context ctx = model.createContext();
 * ctx.setSystemMessage("You are a helpful assistant.");
 * ctx.chat("What is the capital of France?");
 * ctx.chat("What about Germany?");
 * }</pre>
 *
 * <p>Implementations must be thread-safe.
 */
public interface Model extends AutoCloseable {
  /**
   * Returns the name of the underlying model.
   *
   * <p>This is the identifier used when communicating with the backend
   * (e.g. {@code "gpt-4"}, {@code "claude-3-opus-20240229"}, {@code "llama3"}).
   *
   * @return the model name
   */
  String name();

  /**
   * Sends a chat completion request and returns the complete response.
   *
   * <p>This is a blocking call that waits for the full response to be
   * generated before returning.
   *
   * @param request the request parameters including messages and generation settings
   * @return the complete response
   * @throws CommunicationException if the request fails due to network, authentication, or API
   *                                errors
   */
  ChatResponse chat(ChatRequest request);

  /**
   * Sends a streaming chat completion request.
   *
   * <p>Tokens are delivered to {@link StreamHandler#onToken(String)} as they
   * are generated by the model. When the stream completes,
   * {@link StreamHandler#onComplete(ChatResponse)}
   * is called with the aggregated response metadata. If an error occurs,
   * {@link StreamHandler#onError(Throwable)} is called.
   *
   * <p>This method blocks until the stream ends or an error occurs.
   *
   * @param request the request parameters
   * @param handler callbacks for tokens, completion, and errors
   * @throws CommunicationException if the request fails before streaming begins
   */
  void chatStream(ChatRequest request, StreamHandler handler);

  /**
   * Creates a new {@link Context} backed by this model.
   *
   * <p>The context manages conversation history automatically, appending
   * user messages and assistant responses as the conversation progresses.
   *
   * @return a new, empty conversation context
   */
  Context createContext();

  /**
   * Releases any resources held by this model.
   *
   * <p>Once closed, subsequent calls to {@link #chat} or {@link #chatStream}
   * may throw {@link IllegalStateException}.
   */
  @Override
  void close();
}
