/*
 * MIT License
 *
 * Copyright (c) 2026 Mellowhue
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

package net.nanitu.ai;

/**
 * Receives callbacks during a streaming chat completion.
 *
 * <p>Implement this interface to process tokens as they are generated by
 * {@link Model#chatStream(ChatRequest, StreamHandler)}. Each token is delivered
 * via {@link #onToken(String)} as soon as it is available, allowing real-time
 * display of partial results.
 */
public interface StreamHandler {
  /**
   * Called when a new token is generated.
   *
   * <p>May be called zero or more times during a single streamed response.
   * The concatenation of all token strings forms the complete response text.
   *
   * @param token a text fragment generated by the model
   */
  void onToken(String token);

  /**
   * Called when the stream has completed successfully.
   *
   * <p>The {@code response} parameter contains the aggregated result
   * including token usage metadata.
   *
   * @param response the complete response metadata
   */
  default void onComplete(ChatResponse response) {
  }

  /**
   * Called when the stream encounters an error.
   *
   * <p>After this callback, no further calls to {@link #onToken} or
   * {@link #onComplete} will be made.
   *
   * @param error the error that caused the stream to fail
   */
  default void onError(Throwable error) {
  }
}
